name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    outputs:
      version: ${{ steps.version.outputs.current-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
  
      - name: Install Dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      - name: Get current date
        if: matrix.platform == 'windows-latest'
        run: echo "CURRENT_DATE=$(Get-Date -Format "yyyy-MM-dd")" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Cache CLI cargo target
        uses: actions/cache@v2
        with:
          path: src-tauri/target
          key: ${{ matrix.platform }}-stable-cargo-cli-${{ hashFiles('src-tauri/Cargo.lock') }}-${{ env.CURRENT_DATE }}
          restore-keys: |
            ${{ matrix.platform }}-stable-cargo-cli-${{ hashFiles('src-tauri/Cargo.lock') }}
            ${{ matrix.platform }}-stable-cargo-cli-

        
      - name : Build Web 
        run: npm i && npm run build:web
      - run: npm i 
      - run: npm run build:web

      - name: Get version from package.json
        id: version
        uses: martinbeentjes/npm-get-version-action@main
      - name: Build Tauri
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
        with:
          tagName: v${{ steps.version.outputs.current-version }}
          releaseName: v${{ steps.version.outputs.current-version }}
          releaseBody: |
           - Release version  __VERSION__ ,full changelog will be added later.    
           - Commit: [${{env.SHORT_SHA}}](https://github.com/kamyroll/kamyroll-tauri/commit/${{ env.SHORT_SHA }})

  winget-releaser:
    needs: release
    runs-on: windows-latest # Action can only be run on windows

    steps:
      - uses: vedantmgoyal2009/winget-releaser@v1
        with:
          identifier: Kamyroll.Kamyroll-Tauri
          version: v${{ needs.release.outputs.version }}
          release-tag: v${{ needs.release.outputs.version }}
          token: ${{ secrets.WINGET_TOKEN }}
