name: "test-on-pr"
on: [pull_request]

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
         platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: install dependencies (ubuntu only)
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
    - name: Get current date
      run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      if: matrix.platform == 'macos-latest' || matrix.platform == 'ubuntu-latest'

    - name: Get current date
      if: matrix.platform == 'windows-latest'
      run: echo "CURRENT_DATE=$(Get-Date -Format "yyyy-MM-dd")" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Cache CLI cargo target
      uses: actions/cache@v2
      with:
          path: src-tauri/target
          # Add date to the cache to keep it up to date
          key: ${{ matrix.platform }}-stable-cargo-cli-${{ hashFiles('src-tauri/Cargo.lock') }}-${{ env.CURRENT_DATE }}
          # Restore from outdated cache for speed
          restore-keys: |
            ${{ matrix.platform }}-stable-cargo-cli-${{ hashFiles('src-tauri/Cargo.lock') }}
            ${{ matrix.platform }}-stable-cargo-cli-    
    
    - name: install app dependencies and build it
      run: npm i && npm run build:web
    
    - name : Get commit hash (Linux and MacOS)
      if: matrix.platform == 'macos-latest' || matrix.platform == 'ubuntu-latest'
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    - name : Get commit hash (Windows)
      if: matrix.platform == 'windows-latest'
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - uses: tauri-apps/tauri-action@v0
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
      with:
          tagName: v__VERSION__-PR+${{env.SHORT_SHA}}
          releaseName: v__VERSION__-PR+${{env.SHORT_SHA}}
          releaseBody: |
            - __VERSION__-PR+${{env.SHORT_SHA}}
            - This is a pull_request release, please report any bugs you find. It's definitely not stable and shouldn't be used.
            - You can find the changelog [here](https://github.com/kamyroll/Kamyroll-Tauri/blob/dev/changelog.md).
            - **Full Changelog**: https://github.com/kamyroll/Kamyroll-Tauri/compare/v1.0.4...v__VERSION__-PR+${{env.SHORT_SHA}}
          includeDebug: true
          prerelease: true
